// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AgentInstance struct {
	ID               string      `json:"id"`
	Type             AgentType   `json:"type"`
	Name             string      `json:"name"`
	Status           AgentStatus `json:"status"`
	CurrentTask      string      `json:"currentTask"`
	CumulativeImpact string      `json:"cumulativeImpact"`
	PolicyViolations int         `json:"policyViolations"`
}

type AgentRun struct {
	ID          string                `json:"id"`
	TraceID     string                `json:"traceId"`
	BusinessID  string                `json:"businessId"`
	Objective   *Objective            `json:"objective"`
	Status      AgentStatus           `json:"status"`
	Day         int                   `json:"day"`
	Seed        int                   `json:"seed"`
	Agents      []*AgentInstance      `json:"agents"`
	Proposals   []*ExperimentProposal `json:"proposals"`
	Experiments []*Experiment         `json:"experiments"`
	ModelStats  []*ModelRunStats      `json:"modelStats"`
	Metrics     *BusinessMetrics      `json:"metrics"`
	CreatedAt   time.Time             `json:"createdAt"`
	UpdatedAt   time.Time             `json:"updatedAt"`
}

type Business struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Seed        int              `json:"seed"`
	Metrics     *BusinessMetrics `json:"metrics"`
	ActiveRun   *AgentRun        `json:"activeRun,omitempty"`
}

type BusinessMetrics struct {
	Orders               int     `json:"orders"`
	ConversionRate       float64 `json:"conversionRate"`
	RepeatPurchaseRate   float64 `json:"repeatPurchaseRate"`
	Subscribers          int     `json:"subscribers"`
	QualifiedSubscribers int     `json:"qualifiedSubscribers"`
	ExperimentSpendUsd   float64 `json:"experimentSpendUsd"`
}

type CreateRunInput struct {
	BusinessID    string   `json:"businessId"`
	ObjectiveKind string   `json:"objectiveKind"`
	TargetValue   *float64 `json:"targetValue,omitempty"`
	BudgetUsd     *float64 `json:"budgetUsd,omitempty"`
	Seed          *int     `json:"seed,omitempty"`
	LiveModel     *bool    `json:"liveModel,omitempty"`
}

type EvalCaseResult struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Category      string  `json:"category"`
	Passed        bool    `json:"passed"`
	Deterministic bool    `json:"deterministic"`
	Score         float64 `json:"score"`
	Details       string  `json:"details"`
}

type EvalReport struct {
	ID             string            `json:"id"`
	Passed         bool              `json:"passed"`
	ReleaseBlocked bool              `json:"releaseBlocked"`
	Total          int               `json:"total"`
	PassedCount    int               `json:"passedCount"`
	Cases          []*EvalCaseResult `json:"cases"`
	CreatedAt      time.Time         `json:"createdAt"`
}

type Experiment struct {
	ID         string              `json:"id"`
	Proposal   *ExperimentProposal `json:"proposal"`
	Status     AgentStatus         `json:"status"`
	ApprovedAt *time.Time          `json:"approvedAt,omitempty"`
	Result     *ExperimentResult   `json:"result,omitempty"`
}

type ExperimentProposal struct {
	ID                string      `json:"id"`
	Version           int         `json:"version"`
	AgentType         AgentType   `json:"agentType"`
	Hypothesis        string      `json:"hypothesis"`
	ToolName          string      `json:"toolName"`
	ToolArgumentsJSON string      `json:"toolArgumentsJson"`
	PrimaryMetric     string      `json:"primaryMetric"`
	ExpectedOutcome   string      `json:"expectedOutcome"`
	BudgetUsd         float64     `json:"budgetUsd"`
	SuccessThreshold  string      `json:"successThreshold"`
	StopCondition     string      `json:"stopCondition"`
	EvidenceIds       []string    `json:"evidenceIds"`
	Confidence        float64     `json:"confidence"`
	Status            AgentStatus `json:"status"`
	RequiresApproval  bool        `json:"requiresApproval"`
	PolicyReasons     []string    `json:"policyReasons"`
}

type ExperimentResult struct {
	PrimaryMetric    string  `json:"primaryMetric"`
	Baseline         float64 `json:"baseline"`
	Observed         float64 `json:"observed"`
	SampleSize       int     `json:"sampleSize"`
	SpendUsd         float64 `json:"spendUsd"`
	Successful       bool    `json:"successful"`
	StopConditionMet bool    `json:"stopConditionMet"`
	Summary          string  `json:"summary"`
}

type ModelComparison struct {
	ModelID                  string   `json:"modelId"`
	Executed                 bool     `json:"executed"`
	Source                   string   `json:"source"`
	Score                    *float64 `json:"score,omitempty"`
	PolicyViolations         *int     `json:"policyViolations,omitempty"`
	ToolCallSuccessRate      *float64 `json:"toolCallSuccessRate,omitempty"`
	StructuredOutputFailures *int     `json:"structuredOutputFailures,omitempty"`
	LatencyMs                *int     `json:"latencyMs,omitempty"`
	TotalTokens              *int     `json:"totalTokens,omitempty"`
	EstimatedCostUsd         *float64 `json:"estimatedCostUsd,omitempty"`
	Retries                  *int     `json:"retries,omitempty"`
	Note                     string   `json:"note"`
}

type ModelProfile struct {
	ID                 string `json:"id"`
	SupportsJSONSchema bool   `json:"supportsJsonSchema"`
	SupportsTools      bool   `json:"supportsTools"`
	IsFreeAllowed      bool   `json:"isFreeAllowed"`
	Purpose            string `json:"purpose"`
}

type ModelRunStats struct {
	RequestedModel        string  `json:"requestedModel"`
	ResolvedModel         string  `json:"resolvedModel"`
	Source                string  `json:"source"`
	LatencyMs             int     `json:"latencyMs"`
	PromptTokens          int     `json:"promptTokens"`
	CompletionTokens      int     `json:"completionTokens"`
	EstimatedCostUsd      float64 `json:"estimatedCostUsd"`
	Retries               int     `json:"retries"`
	StructuredOutputValid bool    `json:"structuredOutputValid"`
}

type Mutation struct {
}

type Objective struct {
	ID          string  `json:"id"`
	Kind        string  `json:"kind"`
	Description string  `json:"description"`
	TargetValue float64 `json:"targetValue"`
	BudgetUsd   float64 `json:"budgetUsd"`
}

type Query struct {
}

type ReplayInput struct {
	RunID    string   `json:"runId"`
	ModelIds []string `json:"modelIds"`
}

type ReplayResult struct {
	ScenarioSeed int                `json:"scenarioSeed"`
	Comparisons  []*ModelComparison `json:"comparisons"`
}

type TraceEvent struct {
	ID           string    `json:"id"`
	TraceID      string    `json:"traceId"`
	Sequence     int       `json:"sequence"`
	Category     string    `json:"category"`
	Title        string    `json:"title"`
	Summary      string    `json:"summary"`
	EvidenceJSON string    `json:"evidenceJson"`
	CreatedAt    time.Time `json:"createdAt"`
}

type AgentStatus string

const (
	AgentStatusProposed         AgentStatus = "PROPOSED"
	AgentStatusPolicyChecked    AgentStatus = "POLICY_CHECKED"
	AgentStatusAwaitingApproval AgentStatus = "AWAITING_APPROVAL"
	AgentStatusApproved         AgentStatus = "APPROVED"
	AgentStatusRunning          AgentStatus = "RUNNING"
	AgentStatusEvaluating       AgentStatus = "EVALUATING"
	AgentStatusWinning          AgentStatus = "WINNING"
	AgentStatusLosing           AgentStatus = "LOSING"
	AgentStatusPaused           AgentStatus = "PAUSED"
	AgentStatusRetired          AgentStatus = "RETIRED"
	AgentStatusFailed           AgentStatus = "FAILED"
)

var AllAgentStatus = []AgentStatus{
	AgentStatusProposed,
	AgentStatusPolicyChecked,
	AgentStatusAwaitingApproval,
	AgentStatusApproved,
	AgentStatusRunning,
	AgentStatusEvaluating,
	AgentStatusWinning,
	AgentStatusLosing,
	AgentStatusPaused,
	AgentStatusRetired,
	AgentStatusFailed,
}

func (e AgentStatus) IsValid() bool {
	switch e {
	case AgentStatusProposed, AgentStatusPolicyChecked, AgentStatusAwaitingApproval, AgentStatusApproved, AgentStatusRunning, AgentStatusEvaluating, AgentStatusWinning, AgentStatusLosing, AgentStatusPaused, AgentStatusRetired, AgentStatusFailed:
		return true
	}
	return false
}

func (e AgentStatus) String() string {
	return string(e)
}

func (e *AgentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentStatus", str)
	}
	return nil
}

func (e AgentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AgentType string

const (
	AgentTypeSupervisor AgentType = "SUPERVISOR"
	AgentTypeStore      AgentType = "STORE"
	AgentTypeNotify     AgentType = "NOTIFY"
	AgentTypeGive       AgentType = "GIVE"
)

var AllAgentType = []AgentType{
	AgentTypeSupervisor,
	AgentTypeStore,
	AgentTypeNotify,
	AgentTypeGive,
}

func (e AgentType) IsValid() bool {
	switch e {
	case AgentTypeSupervisor, AgentTypeStore, AgentTypeNotify, AgentTypeGive:
		return true
	}
	return false
}

func (e AgentType) String() string {
	return string(e)
}

func (e *AgentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentType", str)
	}
	return nil
}

func (e AgentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DecisionAction string

const (
	DecisionActionKeep            DecisionAction = "KEEP"
	DecisionActionPause           DecisionAction = "PAUSE"
	DecisionActionRetire          DecisionAction = "RETIRE"
	DecisionActionRequestMoreData DecisionAction = "REQUEST_MORE_DATA"
)

var AllDecisionAction = []DecisionAction{
	DecisionActionKeep,
	DecisionActionPause,
	DecisionActionRetire,
	DecisionActionRequestMoreData,
}

func (e DecisionAction) IsValid() bool {
	switch e {
	case DecisionActionKeep, DecisionActionPause, DecisionActionRetire, DecisionActionRequestMoreData:
		return true
	}
	return false
}

func (e DecisionAction) String() string {
	return string(e)
}

func (e *DecisionAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DecisionAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DecisionAction", str)
	}
	return nil
}

func (e DecisionAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DecisionAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DecisionAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
