"use client";

import { useEffect, useMemo, useState } from "react";
import { graphql, type Proposal, type Run } from "@/lib/graphql";

type Stage = "ready" | "proposed" | "approved" | "complete";
type Business = { id: string; name: string; description: string; seed: number; metrics: { orders: number; conversionRate: number; repeatPurchaseRate: number; subscribers: number } };

const BUSINESS_QUERY = `query { business(id:"cosmic-cats") { id name description seed metrics { orders conversionRate repeatPurchaseRate subscribers } } }`;
const CREATE_RUN = `mutation($input:CreateRunInput!){createRun(input:$input){id traceId status day agents{id type name status currentTask cumulativeImpact} proposals{id} experiments{id} modelStats{requestedModel resolvedModel source latencyMs promptTokens completionTokens estimatedCostUsd retries}}}`;
const PROPOSE = `mutation($id:ID!){generateProposals(runId:$id){id agentType hypothesis toolName toolArgumentsJson primaryMetric expectedOutcome budgetUsd successThreshold stopCondition evidenceIds confidence status requiresApproval policyReasons}}`;
const APPROVE = `mutation($id:ID!){approveExperiment(id:$id){id status}}`;
const ADVANCE = `mutation($id:ID!){advanceSimulation(runId:$id,days:7){id traceId status day agents{id type name status currentTask cumulativeImpact} proposals{id agentType hypothesis toolName toolArgumentsJson primaryMetric expectedOutcome budgetUsd successThreshold stopCondition evidenceIds confidence status requiresApproval policyReasons} experiments{id status proposal{id agentType hypothesis toolName toolArgumentsJson primaryMetric expectedOutcome budgetUsd successThreshold stopCondition evidenceIds confidence status requiresApproval policyReasons} result{primaryMetric observed summary successful stopConditionMet}} modelStats{requestedModel resolvedModel source latencyMs promptTokens completionTokens estimatedCostUsd retries}}}`;
const TRACES = `query($id:ID!){traces(runId:$id){id sequence category title summary evidenceJson createdAt}}`;

export function Demo() {
  const [business, setBusiness] = useState<Business | null>(null);
  const [run, setRun] = useState<Run | null>(null);
  const [stage, setStage] = useState<Stage>("ready");
  const [selected, setSelected] = useState(0);
  const [traces, setTraces] = useState<{ id: string; sequence: number; category: string; title: string; summary: string }[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [working, setWorking] = useState(false);
  useEffect(() => { graphql<{ business: Business }>(BUSINESS_QUERY).then(({ business }) => setBusiness(business)).catch((e: Error) => setError(`Backend unavailable: ${e.message}`)); }, []);
  const proposals = run?.proposals ?? [];
  const selectedProposal = proposals[selected] ?? null;
  const step = useMemo(() => ({ ready: 1, proposed: 2, approved: 3, complete: 4 }[stage]), [stage]);
  async function start() { setWorking(true); setError(null); try { const created = await graphql<{ createRun: Run }>(CREATE_RUN, { input: { businessId: "cosmic-cats", objectiveKind: "INCREMENTAL_ORDERS", targetValue: 50, budgetUsd: 100, seed: 424242, liveModel: true } }); const generated = await graphql<{ generateProposals: Proposal[] }>(PROPOSE, { id: created.createRun.id }); setRun({ ...created.createRun, proposals: generated.generateProposals }); setStage("proposed"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to start demo"); } finally { setWorking(false); } }
  async function approve() { if (!run) return; setWorking(true); setError(null); try { await Promise.all(proposals.map((p) => graphql(APPROVE, { id: p.id }))); setStage("approved"); } catch (e) { setError(e instanceof Error ? e.message : "Approval failed"); } finally { setWorking(false); } }
  async function advance() { if (!run) return; setWorking(true); setError(null); try { const response = await graphql<{ advanceSimulation: Run }>(ADVANCE, { id: run.id }); setRun(response.advanceSimulation); setStage("complete"); } catch (e) { setError(e instanceof Error ? e.message : "Simulation failed"); } finally { setWorking(false); } }
  async function openTrace() { if (!run) return; try { const response = await graphql<{ traces: typeof traces }>(TRACES, { id: run.id }); setTraces(response.traces); } catch (e) { setError(e instanceof Error ? e.message : "Trace unavailable"); } }
  const metrics = business?.metrics;
  return <main className="appShell">
    <section className="demoHeader"><div><span className="eyebrow">RECRUITER MODE · STEP {step} OF 4</span><h1>Cosmic Cats growth lab</h1><p>Generate 50 incremental orders without exceeding $100 or messaging limits.</p></div><div className="seed">SCENARIO SEED <b>{business?.seed ?? "…"}</b><br/><span>GraphQL → Go → Postgres · zero-cost route</span></div></section>
    <div className="progress" aria-label={`Demo step ${step} of 4`}><i style={{ width: `${step * 25}%` }} /></div>
    {error && <p className="callout" role="alert">{error}</p>}
    {stage === "ready" && <section className="launch panel"><div><span className="status live">{business ? "READY" : "LOADING"}</span><h2>A real business state, not a chat prompt</h2><p>{metrics ? `${metrics.orders} orders · ${(metrics.conversionRate * 100).toFixed(1)}% conversion · ${metrics.subscribers} subscribers · ${(metrics.repeatPurchaseRate * 100).toFixed(0)}% repeat purchase` : "Loading Cosmic Cats from PostgreSQL…"}</p></div><button className="button primary" disabled={!business || working} onClick={start}>{working ? "Starting…" : "Run 7-day simulation →"}</button></section>}
    {stage !== "ready" && <><section className="agentGrid">{proposals.map((p, i) => { const agent = run?.agents.find((a) => a.type === p.agentType); const visibleStatus = stage === "complete" ? (agent?.status ?? p.status) : p.status; return <button key={p.id} className={`agentCard ${selected === i ? "selected" : ""}`} onClick={() => setSelected(i)}><span>{agent?.name ?? `${p.agentType} Agent`}</span><b className={`status ${visibleStatus.toLowerCase()}`}>{visibleStatus}</b><small>{stage === "complete" ? agent?.cumulativeImpact : p.primaryMetric}</small></button>; })}</section>
    {selectedProposal && <section className="split"><article className="panel proposal"><div className="panelTitle"><span>STRUCTURED PROPOSAL</span><span>confidence {selectedProposal.confidence.toFixed(2)}</span></div><h2>{selectedProposal.hypothesis}</h2><dl><div><dt>Tool</dt><dd><code>{selectedProposal.toolName}</code></dd></div><div><dt>Budget</dt><dd>${selectedProposal.budgetUsd.toFixed(2)}</dd></div><div><dt>Primary metric</dt><dd>{selectedProposal.primaryMetric}</dd></div><div><dt>Success</dt><dd>{selectedProposal.successThreshold}</dd></div><div><dt>Evidence</dt><dd>{selectedProposal.evidenceIds.length} verified IDs</dd></div></dl></article><article className="panel authority"><div className="panelTitle"><span>DETERMINISTIC AUTHORITY</span><span className="verified">✓ policy validated</span></div><h2>{selectedProposal.requiresApproval ? "Human approval required" : "Policy checks passed"}</h2><ul><li>Tool allowlisted for the specialist</li><li>Portfolio budget is bounded at $100</li><li>Exact version and arguments are recorded</li><li>Model output cannot calculate metrics or retire agents</li></ul>{stage === "proposed" && <button className="button primary" disabled={working} onClick={approve}>{working ? "Approving…" : "Approve bounded portfolio"}</button>}{stage === "approved" && <button className="button primary" disabled={working} onClick={advance}>{working ? "Advancing…" : "Advance 7 simulated days"}</button>}{stage === "complete" && <button className="button" onClick={openTrace}>Open evidence trace</button>}</article></section>}</>}
    {stage === "complete" && <section className="results panel"><div className="panelTitle"><span>SIMULATED DEMO OUTCOME</span><span>seed 424242 · {run?.day} days</span></div>{run?.experiments.map((experiment) => <div className="resultRow" key={experiment.id}><b>{run.agents.find((a) => a.type === experiment.proposal.agentType)?.name}</b><span className={`status ${experiment.status.toLowerCase()}`}>{experiment.status === "RETIRED" ? "RETIRED" : experiment.status === "WINNING" ? "KEEP" : experiment.status}</span><strong>{experiment.result?.summary}</strong><small>{experiment.result?.primaryMetric}</small></div>)}<p className="callout">The Give Agent is retired only after trusted code observes sufficient simulated evidence and a true stop predicate. LLM authority: none.</p></section>}
    {traces.length > 0 && <section className="trace panel"><div className="panelTitle"><span>TRACE · {run?.traceId}</span><span>structured evidence, no chain-of-thought</span></div>{traces.map((trace) => <div className="traceRow" key={trace.id}><b>{String(trace.sequence).padStart(2, "0")}</b><span>{trace.category}</span><p><strong>{trace.title}</strong> — {trace.summary}</p></div>)}</section>}
  </main>;
}
